[package]
name = "dlog_proof"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8"
sha2 = "0.10"
hex = "0.4"
k256 = { version = "0.13.3", features = ["sha256", "arithmetic"] }
generic-array = "1.1.0"
typenum = "1.15"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"